Upload partially created build artifacts as well
Signed-off-by: Michał Górny <mgorny@quansight.com>

diff --git a/conda_smithy/templates/create_conda_build_artifacts.sh.tmpl b/conda_smithy/templates/create_conda_build_artifacts.sh.tmpl
--- a/conda_smithy/templates/create_conda_build_artifacts.sh.tmpl
+++ b/conda_smithy/templates/create_conda_build_artifacts.sh.tmpl
@@ -125,18 +125,27 @@ if [[ ! -z "$BLD_ARTIFACT_PREFIX" ]]; then
 
     # All our CI services have either GNU tar or bsdtar, and zstd.
     # Keep the command compatible with both!
-    tar -c -f "${BLD_ARTIFACT_PATH}" "${ZSTD}" \
-        "${EXCLUDE_FROM_BUILD_ARTIFACTS[@]/#/--exclude=}" .
+    if ! tar -c -f "${BLD_ARTIFACT_PATH}" "${ZSTD}" \
+            "${EXCLUDE_FROM_BUILD_ARTIFACTS[@]/#/--exclude=}" . &&
+        [[ -s ${BLD_ARTIFACT_PATH} ]]
+    then
+        # If tar failed but produced a (partial?) file, upload it as "broken".
+        mv -v "${BLD_ARTIFACT_PATH}" "${BLD_ARTIFACT_PATH/%.tar.zst/-broken&}"
+        BLD_ARTIFACT_NAME+=-broken
+        BLD_ARTIFACT_PATH=${BLD_ARTIFACT_PATH/%.tar.zst/-broken&}
+    fi
 
-    echo "BLD_ARTIFACT_NAME: $BLD_ARTIFACT_NAME"
-    echo "BLD_ARTIFACT_PATH: $BLD_ARTIFACT_PATH"
+    if [[ -s ${BLD_ARTIFACT_PATH} ]]; then
+        echo "BLD_ARTIFACT_NAME: $BLD_ARTIFACT_NAME"
+        echo "BLD_ARTIFACT_PATH: $BLD_ARTIFACT_PATH"
 
-    if [[ "$CI" == "azure" ]]; then
-        echo "##vso[task.setVariable variable=BLD_ARTIFACT_NAME]$BLD_ARTIFACT_NAME"
-        echo "##vso[task.setVariable variable=BLD_ARTIFACT_PATH]$BLD_ARTIFACT_PATH"
-    elif [[ "$CI" == "github_actions" ]]; then
-        echo "BLD_ARTIFACT_NAME=$BLD_ARTIFACT_NAME" >> $GITHUB_OUTPUT
-        echo "BLD_ARTIFACT_PATH=$BLD_ARTIFACT_PATH" >> $GITHUB_OUTPUT
+        if [[ "$CI" == "azure" ]]; then
+            echo "##vso[task.setVariable variable=BLD_ARTIFACT_NAME]$BLD_ARTIFACT_NAME"
+            echo "##vso[task.setVariable variable=BLD_ARTIFACT_PATH]$BLD_ARTIFACT_PATH"
+        elif [[ "$CI" == "github_actions" ]]; then
+            echo "BLD_ARTIFACT_NAME=$BLD_ARTIFACT_NAME" >> $GITHUB_OUTPUT
+            echo "BLD_ARTIFACT_PATH=$BLD_ARTIFACT_PATH" >> $GITHUB_OUTPUT
+        fi
     fi
 fi
 
@@ -147,18 +156,27 @@ if [[ ! -z "$WRK_ARTIFACT_PREFIX" && -n ${WORK_PATHS[@]} ]]; then
 
     # All our CI services have either GNU tar or bsdtar, and zstd.
     # Keep the command compatible with both!
-    tar -c -f "${WRK_ARTIFACT_PATH}" "${ZSTD}" \
-        "${EXCLUDE_FROM_WORK[@]/#/--exclude=}" "${WORK_PATHS[@]}"
+    if ! tar -c -f "${WRK_ARTIFACT_PATH}" "${ZSTD}" \
+            "${EXCLUDE_FROM_WORK[@]/#/--exclude=}" "${WORK_PATHS[@]}" &&
+        [[ -s ${WRK_ARTIFACT_PATH} ]]
+    then
+        # If tar failed but produced a (partial?) file, upload it as "broken".
+        mv -v "${WRK_ARTIFACT_PATH}" "${WRK_ARTIFACT_PATH/%.tar.zst/-broken&}"
+        WRK_ARTIFACT_NAME+=-broken
+        WRK_ARTIFACT_PATH=${WRK_ARTIFACT_PATH/%.tar.zst/-broken&}
+    fi
 
-    echo "WRK_ARTIFACT_NAME: $WRK_ARTIFACT_NAME"
-    echo "WRK_ARTIFACT_PATH: $WRK_ARTIFACT_PATH"
+    if [[ -s ${WRK_ARTIFACT_PATH} ]]; then
+        echo "WRK_ARTIFACT_NAME: $WRK_ARTIFACT_NAME"
+        echo "WRK_ARTIFACT_PATH: $WRK_ARTIFACT_PATH"
 
-    if [[ "$CI" == "azure" ]]; then
-        echo "##vso[task.setVariable variable=WRK_ARTIFACT_NAME]$WRK_ARTIFACT_NAME"
-        echo "##vso[task.setVariable variable=WRK_ARTIFACT_PATH]$WRK_ARTIFACT_PATH"
-    elif [[ "$CI" == "github_actions" ]]; then
-        echo "WRK_ARTIFACT_NAME=$WRK_ARTIFACT_NAME" >> $GITHUB_OUTPUT
-        echo "WRK_ARTIFACT_PATH=$WRK_ARTIFACT_PATH" >> $GITHUB_OUTPUT
+        if [[ "$CI" == "azure" ]]; then
+            echo "##vso[task.setVariable variable=WRK_ARTIFACT_NAME]$WRK_ARTIFACT_NAME"
+            echo "##vso[task.setVariable variable=WRK_ARTIFACT_PATH]$WRK_ARTIFACT_PATH"
+        elif [[ "$CI" == "github_actions" ]]; then
+            echo "WRK_ARTIFACT_NAME=$WRK_ARTIFACT_NAME" >> $GITHUB_OUTPUT
+            echo "WRK_ARTIFACT_PATH=$WRK_ARTIFACT_PATH" >> $GITHUB_OUTPUT
+        fi
     fi
 fi
 
@@ -167,17 +185,26 @@ if [[ ! -z "$ENV_ARTIFACT_PREFIX" && -n ${ENVIRONMENT_PATHS[@]} ]]; then
     export ENV_ARTIFACT_NAME="${ENV_ARTIFACT_PREFIX}_${ARTIFACT_UNIQUE_ID}"
     export ENV_ARTIFACT_PATH="${ARTIFACT_STAGING_DIR}/${FEEDSTOCK_NAME}_${ENV_ARTIFACT_PREFIX}_${ARCHIVE_UNIQUE_ID}.tar.zst"
 
-    tar -c -f "${ENV_ARTIFACT_PATH}" "${ZSTD}" "${ENVIRONMENT_PATHS[@]}"
+    if ! tar -c -f "${ENV_ARTIFACT_PATH}" "${ZSTD}" "${ENVIRONMENT_PATHS[@]}" &&
+        [[ -s ${ENV_ARTIFACT_PATH} ]]
+    then
+        # If tar failed but produced a (partial?) file, upload it as "broken".
+        mv -v "${ENV_ARTIFACT_PATH}" "${ENV_ARTIFACT_PATH/%.tar.zst/-broken&}"
+        ENV_ARTIFACT_NAME+=-broken
+        ENV_ARTIFACT_PATH=${ENV_ARTIFACT_PATH/%.tar.zst/-broken&}
+    fi
 
-    echo "ENV_ARTIFACT_NAME: $ENV_ARTIFACT_NAME"
-    echo "ENV_ARTIFACT_PATH: $ENV_ARTIFACT_PATH"
+    if [[ -s ${ENV_ARTIFACT_PATH} ]]; then
+        echo "ENV_ARTIFACT_NAME: $ENV_ARTIFACT_NAME"
+        echo "ENV_ARTIFACT_PATH: $ENV_ARTIFACT_PATH"
 
-    if [[ "$CI" == "azure" ]]; then
-        echo "##vso[task.setVariable variable=ENV_ARTIFACT_NAME]$ENV_ARTIFACT_NAME"
-        echo "##vso[task.setVariable variable=ENV_ARTIFACT_PATH]$ENV_ARTIFACT_PATH"
-    elif [[ "$CI" == "github_actions" ]]; then
-        echo "ENV_ARTIFACT_NAME=$ENV_ARTIFACT_NAME" >> $GITHUB_OUTPUT
-        echo "ENV_ARTIFACT_PATH=$ENV_ARTIFACT_PATH" >> $GITHUB_OUTPUT
+        if [[ "$CI" == "azure" ]]; then
+            echo "##vso[task.setVariable variable=ENV_ARTIFACT_NAME]$ENV_ARTIFACT_NAME"
+            echo "##vso[task.setVariable variable=ENV_ARTIFACT_PATH]$ENV_ARTIFACT_PATH"
+        elif [[ "$CI" == "github_actions" ]]; then
+            echo "ENV_ARTIFACT_NAME=$ENV_ARTIFACT_NAME" >> $GITHUB_OUTPUT
+            echo "ENV_ARTIFACT_PATH=$ENV_ARTIFACT_PATH" >> $GITHUB_OUTPUT
+        fi
     fi
 fi
 
