tighten up volume options handling

diff --git a/conda_smithy/templates/run_docker_build.tmpl b/conda_smithy/templates/run_docker_build.tmpl
--- a/conda_smithy/templates/run_docker_build.tmpl
+++ b/conda_smithy/templates/run_docker_build.tmpl
@@ -48,54 +48,27 @@ if hash docker-machine 2> /dev/null && docker-machine active > /dev/null; then
     HOST_USER_ID=$(docker-machine ssh $(docker-machine active) id -u)
 fi
 
-# By default, the feedstock is mounted read-only (ro) and the build_artifacts
-# read/write (rw).
-#
-# ADVANCED
-#
-#     For live debugging inside the container, you can mount the feedstock
-#     read-writeable with:
-#
-#     CF_FEEDSTOCK_VOLUME_OPTIONS=rw ./run_docker_build.sh
-#
-# SELinux
-#
-#     ** WARNING: this can be very unsafe, see considerations here: **
-#     https://github.com/moby/moby/issues/30934
-#
-#     For SELinux enforcing hosts, you may temporarily change the HOST labels
-#     with:
-#
-#     CF_FEEDSTOCK_VOLUME_OPTIONS=ro,Z CF_ARTIFACTS_VOLUME_OPTIONS=rw,Z \
-#       /run_docker_build.sh
-#
-if [ -n "${CF_FEEDSTOCK_VOLUME_OPTIONS+set}" ]; then
-    CF_FEEDSTOCK_VOLUME_OPTIONS=ro
-fi
-if [ -n "${CF_ARTIFACTS_VOLUME_OPTIONS+set}" ]; then
-    CF_ARTIFACTS_VOLUME_OPTIONS=rw
-fi
-
 mkdir -p $ARTIFACTS_ROOT
-rm -f "$ARTIFACTS_ROOT/conda-forge-build-done" \
-    "$ARTIFACTS_ROOT/conda-forge-build-starting"
-touch "$ARTIFACTS_ROOT/conda-forge-build-starting"
+
+rm -f "$ARTIFACTS_ROOT/conda-forge-build-done"
 
 cat << EOF | {{ docker.executable }} run -i \
-                        -v "${FEEDSTOCK_ROOT}":/home/conda/feedstock_root:${CF_FEEDSTOCK_VOLUME_OPTIONS} \
-                        -v "${ARTIFACTS_ROOT}":/home/conda/build_artifacts:${CF_ARTIFACTS_VOLUME_OPTIONS} \
-                        {{ matrix_env_vars(matrix) }}
-                        -a stdin -a stdout -a stderr \
-                        {{ docker.image }} \
-                        {{ docker.command }} || exit 1
+    -v "${FEEDSTOCK_ROOT}":/home/conda/feedstock_root:${CF_FEEDSTOCK_VOLUME_OPTIONS:-ro} \
+    -v "${ARTIFACTS_ROOT}":/home/conda/build_artifacts:${CF_ARTIFACTS_VOLUME_OPTIONS:-rw} \
+    {{ matrix_env_vars(matrix) }}
+    -a stdin -a stdout -a stderr \
+    {{ docker.image }} \
+    {{ docker.command }} || exit 1
 
-ls /home/conda/feedstock_root/ > /dev/null || \
-  echo "ERROR: ${FEEDSTOCK_ROOT} is not readable in the container!" &&
+if [[ ! -r /home/conda/feedstock_root/recipe/meta.yaml ]]; then
+  echo "ERROR: "${FEEDSTOCK_ROOT}" is not readable in the container"
   exit 1
+fi
 
-rm -f /home/build_artifacts/conda-forge-build-starting > /dev/null || \
-  echo "ERROR: ${ARTIFACTS_ROOT} is not writeable in the container!" &&
+if [[ ! -w /home/conda/build_artifacts ]]; then
+  echo "ERROR: ${ARTIFACTS_ROOT} is not writeable in the container"
   exit 1
+fi
 
 set -e
 set +x
