Use the snippet from https://github.com/conda-forge/conda-smithy/pull/2430#issuecomment-3594330317
Signed-off-by: Michał Górny <mgorny@quansight.com>

diff --git a/conda_smithy/templates/run_osx_build.sh.tmpl b/conda_smithy/templates/run_osx_build.sh.tmpl
--- a/conda_smithy/templates/run_osx_build.sh.tmpl
+++ b/conda_smithy/templates/run_osx_build.sh.tmpl
@@ -123,9 +123,24 @@ if [[ "${sha:-}" == "" ]]; then
 fi
 
 {% if build_setup -%}
-export OSX_SDK_DIR=/opt/conda-sdks
-/usr/bin/sudo mkdir -p "${OSX_SDK_DIR}"
-/usr/bin/sudo chown "${USER}" "${OSX_SDK_DIR}"
+if [[ "${OSX_SDK_DIR:-}" == "" ]]; then
+  if [[ "${CI:-}" == "" ]]; then
+    OSX_SDK_DIR=$(mktemp -d)
+  else
+    # here we're definitely in the CI case
+    export OSX_SDK_DIR=/opt/conda-sdks
+    /usr/bin/sudo mkdir -p "${OSX_SDK_DIR}"
+    /usr/bin/sudo chown "${USER}" "${OSX_SDK_DIR}"
+  fi
+else
+  if tmpf=$(mktemp -p "$OSX_SDK_DIR" tmp.XXXXXXXX 2>/dev/null); then
+      rm -f "$tmpf"
+      echo "OSX_SDK_DIR is writeable without sudo, continuing"
+  else
+      echo "User-provided OSX_SDK_DIR is not writeable for current user! Aborting"
+      exit 1
+  fi
+fi
 
 echo -e "\n\nRunning the build setup script."
 {{ build_setup }}
