Sync osx to win, part 1
Signed-off-by: Michał Górny <mgorny@quansight.com>

diff --git a/conda_smithy/templates/run_osx_build.sh.tmpl b/conda_smithy/templates/run_osx_build.sh.tmpl
--- a/conda_smithy/templates/run_osx_build.sh.tmpl
+++ b/conda_smithy/templates/run_osx_build.sh.tmpl
@@ -28,58 +28,78 @@ export CONFIG_FILE="${CI_SUPPORT}/${CONFIG}.yaml"
 {%- if conda_install_tool == "micromamba" %}
 
 ( startgroup "Provisioning base env with micromamba" ) 2> /dev/null
+
+MAMBA_ROOT_PREFIX="${MINIFORGE_HOME}-micromamba-$(date +%s)"
 MICROMAMBA_VERSION="1.5.10-0"
 if [[ "$(uname -m)" == "arm64" ]]; then
-  osx_arch="osx-arm64"
+    osx_arch="osx-arm64"
 else
-  osx_arch="osx-64"
+    osx_arch="osx-64"
 fi
 MICROMAMBA_URL="https://github.com/mamba-org/micromamba-releases/releases/download/${MICROMAMBA_VERSION}/micromamba-${osx_arch}"
-MAMBA_ROOT_PREFIX="${MINIFORGE_HOME}-micromamba-$(date +%s)"
+MICROMAMBA_TMPDIR=$(mktemp -d)
+MICROMAMBA_EXE=${MICROMAMBA_TMPDIR}/micromamba
+
 echo "Downloading micromamba ${MICROMAMBA_VERSION}"
-micromamba_exe="$(mktemp -d)/micromamba"
-curl -L -o "${micromamba_exe}" "${MICROMAMBA_URL}"
-chmod +x "${micromamba_exe}"
-echo "Creating environment"
-"${micromamba_exe}" create --yes --root-prefix "${MAMBA_ROOT_PREFIX}" --prefix "${MINIFORGE_HOME}" \
-  --channel conda-forge \
-  pip {{ conda_build_tool_deps }} {{ " ".join(remote_ci_setup) }}
+curl -L -o "${MICROMAMBA_EXE}" "${MICROMAMBA_URL}"
+chmod +x "${MICROMAMBA_EXE}"
+
+echo Creating environment
+"${MICROMAMBA_EXE}" create --yes --root-prefix "${MAMBA_ROOT_PREFIX}" --prefix "${MINIFORGE_HOME}" \
+    --channel conda-forge \
+    pip {{ conda_build_tool_deps }} {{ " ".join(remote_ci_setup) }}
 echo "Moving pkgs cache from ${MAMBA_ROOT_PREFIX} to ${MINIFORGE_HOME}"
 mv "${MAMBA_ROOT_PREFIX}/pkgs" "${MINIFORGE_HOME}"
-echo "Cleaning up micromamba"
-rm -rf "${MAMBA_ROOT_PREFIX}" "${micromamba_exe}" || true
+
+echo Cleaning up micromamba
+rm -rf "${MAMBA_ROOT_PREFIX}" "${MICROMAMBA_EXE}" || :
+
 ( endgroup "Provisioning base env with micromamba" ) 2> /dev/null
+
 {%- elif conda_install_tool == "pixi" %}
+
 ( startgroup "Provisioning base env with pixi" ) 2> /dev/null
-mkdir -p "${MINIFORGE_HOME}"
+
+echo Installing pixi
 curl -fsSL https://pixi.sh/install.sh | bash
 export PATH="~/.pixi/bin:$PATH"
+
+echo Installing environment
+mkdir -p "${MINIFORGE_HOME}"
 arch=$(uname -m)
 if [[ "$arch" == "x86_64" ]]; then
   arch="64"
 fi
 PIXI_ENV=build
 sed -i.bak "s/platforms = .*/platforms = [\"osx-${arch}\"]/" pixi.toml
-echo "Creating environment"
 pixi install --environment "${PIXI_ENV}"
 pixi list --environment "${PIXI_ENV}"
-echo "Activating environment"
+
+echo Activating environment
 eval "$(pixi shell-hook --environment "${PIXI_ENV}")"
 mv pixi.toml.bak pixi.toml
+
 ( endgroup "Provisioning base env with pixi" ) 2> /dev/null
+
 {%- else %}
+
 ( startgroup "Installing a fresh version of Miniforge" ) 2> /dev/null
 
+echo Downloading Miniforge
 MINIFORGE_URL="https://github.com/conda-forge/miniforge/releases/latest/download"
 MINIFORGE_FILE="Miniforge3-MacOSX-$(uname -m).sh"
 curl -L -O "${MINIFORGE_URL}/${MINIFORGE_FILE}"
+
+echo Installing Miniforge
 rm -rf "${MINIFORGE_HOME}"
 bash "${MINIFORGE_FILE}" -b -p "${MINIFORGE_HOME}"
 
 ( endgroup "Installing a fresh version of Miniforge" ) 2> /dev/null
+
 {%- endif %}
 
 ( startgroup "Configuring conda" ) 2> /dev/null
+
 {%- if conda_build_tool == "mambabuild" %}
 {%- set BUILD_CMD="conda-mambabuild" %}
 {%- set NO_TEST_FLAG="--no-test" %}
@@ -97,65 +117,78 @@ bash "${MINIFORGE_FILE}" -b -p "${MINIFORGE_HOME}"
 {%- set NO_TEST_FLAG="--no-test" %}
 {%- endif %}
 
+# Activate the base conda environment
 {%- if conda_install_tool != "pixi" %}
-echo "Activating environment"
+echo Activating environment
 source "${MINIFORGE_HOME}/etc/profile.d/conda.sh"
 conda activate base
 {%- endif %}
+
 {%- if conda_solver %}
+# Configure the solver
 export CONDA_SOLVER="{{ conda_solver }}"
 {%- endif %}
 {%- if conda_solver == "libmamba" %}
 export CONDA_LIBMAMBA_SOLVER_NO_CHANNELS_FROM_INSTALLED=1
 {%- endif %}
+
 {%- if conda_install_tool in ("conda", "mamba") %}
+# Provision the necessary dependencies to build the recipe later
+echo Installing dependencies
 {{ conda_install_tool }} install --update-specs --yes --quiet --channel conda-forge --strict-channel-priority \
     pip {{ conda_install_tool_deps }} {{ conda_build_tool_deps }} {{ " ".join(remote_ci_setup) }}
 {%- endif %}
 
 {% if local_ci_setup %}
+echo Overriding conda-forge-ci-setup with local version
 conda uninstall --quiet --yes --force {{ " ".join(remote_ci_setup) }}
 pip install --no-deps "${RECIPE_ROOT}"
 {%- endif %}
-# set up the condarc
+
+# Set basic configuration
+echo Setting up configuration
 setup_conda_rc "${FEEDSTOCK_ROOT}" "${RECIPE_ROOT}" "${CONFIG_FILE}"
 
+# macOS-specific setup
 if [[ "${CI:-}" != "" ]]; then
-  mangle_compiler "${FEEDSTOCK_ROOT}" "${RECIPE_ROOT}" "${CONFIG_FILE}"
+    mangle_compiler "${FEEDSTOCK_ROOT}" "${RECIPE_ROOT}" "${CONFIG_FILE}"
 fi
 
 if [[ "${CI:-}" != "" ]]; then
-  echo "Mangling homebrew in the CI to avoid conflicts."
-  /usr/bin/sudo mangle_homebrew
-  /usr/bin/sudo -k
+    echo "Mangling homebrew in the CI to avoid conflicts."
+    /usr/bin/sudo mangle_homebrew
+    /usr/bin/sudo -k
 else
-  echo "Not mangling homebrew as we are not running in CI"
+    echo "Not mangling homebrew as we are not running in CI"
 fi
 
 if [[ "${sha:-}" == "" ]]; then
-  sha=$(git rev-parse HEAD)
+    sha=$(git rev-parse HEAD)
 fi
 
 {% if build_setup -%}
 if [[ "${OSX_SDK_DIR:-}" == "" ]]; then
-  if [[ "${CI:-}" == "" ]]; then
-    echo "Please set OSX_SDK_DIR to a directory where SDKs can be downloaded to. Aborting"
-    exit 1
-  else
-    export OSX_SDK_DIR=/opt/conda-sdks
-    /usr/bin/sudo mkdir -p "${OSX_SDK_DIR}"
-    /usr/bin/sudo chown "${USER}" "${OSX_SDK_DIR}"
-  fi
+    if [[ "${CI:-}" == "" ]]; then
+        echo "Please set OSX_SDK_DIR to a directory where SDKs can be downloaded to. Aborting"
+        exit 1
+    else
+        export OSX_SDK_DIR=/opt/conda-sdks
+        /usr/bin/sudo mkdir -p "${OSX_SDK_DIR}"
+        /usr/bin/sudo chown "${USER}" "${OSX_SDK_DIR}"
+    fi
 else
-  if tmpf=$(mktemp "$OSX_SDK_DIR"/tmp.XXXXXXXX 2>/dev/null); then
-      rm -f "$tmpf"
-      echo "OSX_SDK_DIR is writeable without sudo, continuing"
-  else
-      echo "User-provided OSX_SDK_DIR is not writeable for current user! Aborting"
-      exit 1
-  fi
+    if tmpf=$(mktemp "$OSX_SDK_DIR"/tmp.XXXXXXXX 2>/dev/null); then
+        rm -f "$tmpf"
+        echo "OSX_SDK_DIR is writeable without sudo, continuing"
+    else
+        echo "User-provided OSX_SDK_DIR is not writeable for current user! Aborting"
+        exit 1
+    fi
 fi
+{%- endif %}
 
+{% if build_setup -%}
+echo Running build setup
 {{ build_setup }}
 {%- endif %}
 
@@ -170,7 +203,8 @@ make_build_number "${FEEDSTOCK_ROOT}" "${RECIPE_ROOT}" "${CONFIG_FILE}"
 {%- endif %}
 
 if [[ -f "${FEEDSTOCK_ROOT}/LICENSE.txt" ]]; then
-  cp "${FEEDSTOCK_ROOT}/LICENSE.txt" "${RECIPE_ROOT}/recipe-scripts-license.txt"
+    echo Copying feedstock license
+    cp "${FEEDSTOCK_ROOT}/LICENSE.txt" "${RECIPE_ROOT}/recipe-scripts-license.txt"
 fi
 
 if [[ "${BUILD_WITH_CONDA_DEBUG:-0}" == 1 ]]; then
@@ -201,59 +235,60 @@ if [[ "${BUILD_WITH_CONDA_DEBUG:-0}" == 1 ]]; then
         --target-platform "${HOST_PLATFORM}"
 
     rattler-build debug shell
+    exit 0
     {%- else %}
     echo "Build tool {{ conda_build_tool }} is not currently supported in debug mode"
     exit 1
     {%- endif %}
-else
-    # differences between conda-build vs. rattler-build
-    #   - recipe is positional vs. --recipe "${RECIPE_ROOT}"
-    #   - --suppress-variables vs. none
-    #   - --clobber-file vs. none
-    #   - none vs. --target-platform
-    #   - --extra-meta a=b c=d vs. --extra-meta a=b --extra-meta c=d
-    {%- if conda_build_tool != "rattler-build" %}
-    CONDA_SUBDIR="${BUILD_PLATFORM}" {{ BUILD_CMD }} \
-        "${RECIPE_ROOT}" \
-        -m "${CI_SUPPORT}/${CONFIG}.yaml" \
-        ${EXTRA_CB_OPTIONS:-} \
-        --suppress-variables \
-        --clobber-file "${CI_SUPPORT}/clobber_${CONFIG}.yaml" \
-        --extra-meta flow_run_id="${flow_run_id:-}" remote_url="${remote_url:-}" sha="${sha:-}"
+fi
 
-    {%- else %}
+# Build the recipe
+echo Building recipe
 
-    {{ BUILD_CMD }} \
-        --recipe "${RECIPE_ROOT}" \
-        -m "${CI_SUPPORT}/${CONFIG}.yaml" \
-        ${EXTRA_CB_OPTIONS:-} \
-        --build-platform "${BUILD_PLATFORM}" \
-        --target-platform "${HOST_PLATFORM}" \
-        --extra-meta flow_run_id="${flow_run_id:-}" \
-        --extra-meta remote_url="${remote_url:-}" \
-        --extra-meta sha="${sha:-}"
+# differences between conda-build vs. rattler-build
+#   - recipe is positional vs. --recipe "${RECIPE_ROOT}"
+#   - --suppress-variables vs. none
+#   - --clobber-file vs. none
+#   - none vs. --target-platform
+#   - --extra-meta a=b c=d vs. --extra-meta a=b --extra-meta c=d
+{%- if conda_build_tool != "rattler-build" %}
+CONDA_SUBDIR="${BUILD_PLATFORM}" {{ BUILD_CMD }} \
+    "${RECIPE_ROOT}" \
+    -m "${CI_SUPPORT}/${CONFIG}.yaml" \
+    ${EXTRA_CB_OPTIONS:-} \
+    --suppress-variables \
+    --clobber-file "${CI_SUPPORT}/clobber_${CONFIG}.yaml" \
+    --extra-meta flow_run_id="${flow_run_id:-}" remote_url="${remote_url:-}" sha="${sha:-}"
 
-    {%- endif %}
-    ( startgroup "Inspecting artifacts" ) 2> /dev/null
+{%- else %}
 
-    # inspect_artifacts was only added in conda-forge-ci-setup 4.9.4
-    command -v inspect_artifacts >/dev/null 2>&1 && inspect_artifacts --recipe-dir "${RECIPE_ROOT}" -m "${CONFIG_FILE}" || echo "inspect_artifacts needs conda-forge-ci-setup >=4.9.4"
+{{ BUILD_CMD }} \
+    --recipe "${RECIPE_ROOT}" \
+    -m "${CI_SUPPORT}/${CONFIG}.yaml" \
+    ${EXTRA_CB_OPTIONS:-} \
+    --build-platform "${BUILD_PLATFORM}" \
+    --target-platform "${HOST_PLATFORM}" \
+    --extra-meta flow_run_id="${flow_run_id:-}" \
+    --extra-meta remote_url="${remote_url:-}" \
+    --extra-meta sha="${sha:-}"
 
-    ( endgroup "Inspecting artifacts" ) 2> /dev/null
+{%- endif %}
 
-    {%- if conda_forge_output_validation %}
-    ( startgroup "Validating outputs" ) 2> /dev/null
+( startgroup "Inspecting artifacts" ) 2> /dev/null
 
-    validate_recipe_outputs "${FEEDSTOCK_NAME}"
+# inspect_artifacts was only added in conda-forge-ci-setup 4.9.4
+command -v inspect_artifacts >/dev/null 2>&1 && inspect_artifacts --recipe-dir "${RECIPE_ROOT}" -m "${CONFIG_FILE}" || echo "inspect_artifacts needs conda-forge-ci-setup >=4.9.4"
 
-    ( endgroup "Validating outputs" ) 2> /dev/null
-    {%- endif %}
+( endgroup "Inspecting artifacts" ) 2> /dev/null
 
+{%- if conda_forge_output_validation %}
+( startgroup "Validating outputs" ) 2> /dev/null
+validate_recipe_outputs "${FEEDSTOCK_NAME}"
+( endgroup "Validating outputs" ) 2> /dev/null
+{%- endif %}
+
+if [[ "${UPLOAD_PACKAGES}" != "False" ]] && [[ "${IS_PR_BUILD}" == "False" ]]; then
     ( startgroup "Uploading packages" ) 2> /dev/null
-
-    if [[ "${UPLOAD_PACKAGES}" != "False" ]] && [[ "${IS_PR_BUILD}" == "False" ]]; then
-        upload_package {% if conda_forge_output_validation %}--validate --feedstock-name="${FEEDSTOCK_NAME}" {% endif %}{% if private_upload %} --private{% endif %} "${FEEDSTOCK_ROOT}" "${RECIPE_ROOT}" "${CONFIG_FILE}"
-    fi
-
+    upload_package {% if conda_forge_output_validation %}--validate --feedstock-name="${FEEDSTOCK_NAME}" {% endif %}{% if private_upload %} --private{% endif %} "${FEEDSTOCK_ROOT}" "${RECIPE_ROOT}" "${CONFIG_FILE}"
     ( endgroup "Uploading packages" ) 2> /dev/null
 fi
